timeout: 3
interface_resolution: 1280x800

backdrop: 1a2b3c
term_background: 802a3b4c
term_foreground: ffffff
term_wallpaper: boot():/boot/limine/boo.png
wallpaper: boot():/boot/limine/boo.png

/AvoryOS Minimal (OpenRC + IceWM)
    protocol: limine
    path: boot():/boot/kernel
    cmdline: init=/sbin/init
    module_path: boot():/disk.img
    module_string: disk.img
    resolution: 1280x800

/AvoryOS Minimal (Rescue Shell)
    protocol: limine
    path: boot():/boot/kernel
    cmdline: init=/bin/bash
    module_path: boot():/disk.img
    module_string: disk.img
    resolution: 1280x800

/AvoryOS Minimal Debug (Rescue Shell + Logs on Screen)
    protocol: limine
    path: boot():/boot/kernel
    cmdline: init=/bin/bash screenlog
    module_path: boot():/disk.img
    module_string: disk.img
    resolution: 1280x800
